{% set name = "opencensus-ext-azure" %}
{% set version = "1.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3fa3472bfbc71d7442375f2c78c1c9b6046cf0d6d2c9408b3944c84f86a30bd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - azure-core >=1.12.0,<2.0.0
    - azure-identity >=1.5.0,<2.0.0
    - opencensus >=0.11.3,<1.0.0
    - psutil >=5.6.3
    - requests >=2.19.0

test:
  imports:
    - opencensus.ext.azure

about:
  home: https://github.com/census-instrumentation/opencensus-python
  license: Apache-2.0
  license_file: LICENSE
  summary: OpenCensus Azure Monitor Exporters
  description: |
    OpenCensus Azure Monitor Exporters. The Azure Monitor Log Handler allows
    you to export Python logs to Azure Monitor.
  doc_url: https://github.com/census-instrumentation/opencensus-python/tree/master/contrib/opencensus-ext-azure/examples
  dev_url: https://github.com/census-instrumentation/opencensus-python/tree/master/contrib/opencensus-ext-azure

extra:
  recipe-maintainers:
    - basnijholt
    - krisevans
    - dhirschfeld
